### ISSUE TITLE
Foto Utama Artikel tidak dapat muncul ketika Share link artikel di WA, Telegram

### ISSUE THREAD

**Issue by mah-mudi** [dikisiswanto/tema-silir#2]
Foto Utama Artikel tidak dapat muncul ketika Share link artikel di WA, Telegram
![silir1](https://user-images.githubusercontent.com/57661283/202367809-8f49c922-7a0c-43c8-ab90-af70d953d3dc.png)

Harapannya, Foto Utama Artikel dapat muncul ketika Share link artikel di WA, Telegram seperti ini
![image](https://user-images.githubusercontent.com/57661283/202367934-54ebbeed-2907-429a-bcb8-e119deeb5209.png)

**Comment by dikisiswanto** [comment]
**Solusi issue ini:**

Untuk artikel baru, opengraph milik Facebook/wa butuh waktu untuk melakukan crawling.

Pastikan gambar utama sudah dikompresi sebelum di upload biar ukuran file gambarnya kecil
